### ISSUE TITLE
Cli crash

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables-cli#5]
Hello,
I tried to simply download and run the cli by typing `cables`.
This is what I get:

```javascript

internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cables/cables/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cables/cables/index.js:9:17)
```

The error seems to come from the `extract-zip` package.

**Comment by kikohs** [comment]
My node version was outdated like most version if you use the default settings.
Make sure to have the latest [node](https://nodejs.org/en/download/) or a LTS version.
